.gitignore, 1.10/scala_2.11-debian/Dockerfile, 1.10/scala_2.12-debian/Dockerfile, 1.9/scala_2.11-debian/Dockerfile, 1.9/scala_2.12-debian/Dockerfile, Dockerfile-debian.template, add-custom.sh, add-version.sh, common.sh
Adds a hook into `add-version.sh` to generate dockerfiles that download the distribution from a configurable URL. Since these likely won't match any GPG signature (as is the case for our nightly snapshots) this check will be skipped.
This required that we pass the URLs directly into the `Dockerfile`, instead of having it generate them from the flink/scala versions.  A new `GPG_SKIP` flag controls whether the signature should be verified.
=> [FLINK-17367] Add configurable download URL

.gitignore, .travis.yml, docker-entrypoint.sh, testing/docker-test-job/pom.xml, testing/docker-test-job/src/main/java/org/apache/flink/StreamingJob.java, testing/run_travis_tests.sh, testing/testing_lib.sh
Adds support for job-clusters.
This PR is also relevant for 1.10, but the commits would be identical.
A job-cluster can be started by passing standalone-job to docker-entrypoint.sh. User artifacts (i.e., the job jar to run) can be passed via the USER_ARTIFACTS environment variable as a list of files/directories, separated with semi-colons (;). This will usually point to some mounted volume.
The script then copies all files into the usrlib directory of the distribution.
The vast majority of this PR is concerned with testing. Since a job-cluster cannot be started without a job to run I added a maven project containing a trivial streaming job that runs infinitely.
The jar is built on CI before the tests are run and provided to the jobmanager as described above.
This PR also removes the diff …
=> [FLINK-17164] Add job-cluster support 

generator.sh
The PR adding the release was rejected by their CI because of this: https://github.com/docker-library/official-images/pull/8459
=> [hotfix] Replace forbidden latest-javaX with javaX

README.md, common.sh, publish-to-dockerhub.sh
I've test-deployed this to my personal GitHub account: https://github.com/rmetzger/flink/packages/561326/versions (the "Latest Version" annotation is wrong, but we would not link this page prominently anyways)
=> [FLINK-20632] Add script to publish docker images to Docker Hub

docker-entrypoint.sh
Removes an odd special code path for taskmanagers started in docker.
=> [FLINK-21036] Remove automatic configuration of number of slots

docker-entrypoint.sh
Based on #58.
One item that specifically needs a discussion is whether it is safe to also set the number of task slots for jobmanager processes. I would generally think so, as any user not setting it themselves may run into consistency issues anyway. (relevant: FLINK-21036)
=> [FLINK-21037] Deduplicate configuration logic 

1.12/scala_2.11-java11-debian/Dockerfile, 1.12/scala_2.11-java11-debian/docker-entrypoint.sh, 1.12/scala_2.11-java11-debian/release.metadata, 1.12/scala_2.11-java8-debian/Dockerfile, 1.12/scala_2.11-java8-debian/docker-entrypoint.sh, 1.12/scala_2.11-java8-debian/release.metadata, 1.12/scala_2.12-java11-debian/Dockerfile, 1.12/scala_2.12-java11-debian/docker-entrypoint.sh, 1.12/scala_2.12-java11-debian/release.metadata, 1.12/scala_2.12-java8-debian/Dockerfile, 1.12/scala_2.12-java8-debian/docker-entrypoint.sh, 1.12/scala_2.12-java8-debian/release.metadata
Temporarily roll master back to 1.12.0, so that we can generate the stackbrew file for 1.12.0.
Once 1.12.0 is on docker hub, we can release 1.12.1 there, so that the latest tag is correct.
Here's the current stackbrew output:
\# this file is generated via https://github.com/apache/flink-docker/blob/f47f4a2e257279c4c28667e3ceff12bc5eb70afb/generate-stackbrew-library.sh
Maintainers: Patrick Lucas <me@patricklucas.com> (@patricklucas),
Ismaël Mejía <iemejia@gmail.com> (@iemejia)
GitRepo: https://github.com/apache/flink-docker.git
Tags: 1.11.3-scala_2.11-java11, 1.11-scala_2.11-java11
Architectures: amd64
GitCommit: 7035f03679b11352f2fdecd9f6a9bb0ec8bc2022
Directory: ./1.11/scala_2.11-java11-debian
Tags: 1.11.3-scala_2.11-java8, 1.11-scala_2.11-java8, 1.11.3-scala_2.11, 1.11-scala_2.11 …
=> Go back to Flink 1.12.0

docker-entrypoint.sh
After FLINK-21128 is done, we could remove the magical classpath setting stuff in docker-entrypoint.sh.
```
export _FLINK_HOME_DETERMINED=true
. $FLINK_HOME/bin/config.sh
export FLINK_CLASSPATH="`constructFlinkClassPath`:$INTERNAL_HADOOP_CLASSPATHS"
```
This is a promised change in https://github.com/docker-library/official-images/pull/9249#issuecomment-768561251.
=> [FLINK-21554] Remove the magical classpath setting stuff in docker-entrypoint.sh

Dockerfile-debian.template
With FLINK-24474, we are going to bind the REST endpoint to `localhost` by default as a security precaution. This PR adds to the dockerfile to update this default setting to bind to `0.0.0.0`, so that Flink binds to a network interface within the container, so that it can communicate with the Docker network layer. This is done within the Dockerfile and not the docker-entrypoint.sh due to FLINK-21383.
=> [FLINK-24474] Bind Rest endpoint addresses to 0.0.0.0 by default

Dockerfile-debian.template
With FLINK-24474, we are going to bind the RPC endpoints to localhost by default as a security precaution. This PR adds to the dockerfile to update this default setting to bind to 0.0.0.0, so that Flink binds the RPC endpoints to a network interface within the container, so that it can communicate with the Docker network layer. This is done within the Dockerfile and not the docker-entrypoint.sh due to FLINK-21383.
=> [FLINK-24474] Bind Jobmanager/Taskmanager RPC endpoint addresses to 0.0.0.0 by default

Dockerfile-debian.template
Reset `taskmanager.host` setting, as we add a default setting in [FLINK-24474](https://issues.apache.org/jira/browse/FLINK-24474) that is not applicable for docker containers.
=> [FLINK-24474] reset taskmanager.host

1.15/scala_2.12-java11-debian/Dockerfile, 1.15/scala_2.12-java8-debian/Dockerfile
@xintongsong This is a companion to https://github.com/apache/flink-docker/pull/122.
=> Update key for 1.15.1 to use full fingerprint

add-version.sh
@xintongsong Please see https://github.com/docker-library/official-images/pull/12750#issuecomment-1176490636 .
The reviewer asked us to redo this with the full fingerprint "so that gpg can verify it".
=> Update key for 1.15.1 to full fingerprint for official-images

README.md
My pull request against official-images wasn't accepted until I updated it to refer to commits in this repo that build images that use the full GPG fingerprint of my signing key. 
This PR updates the README so that others can avoid this problem.
=> [readme] explicitly mention that the full GPG fingerprint is required

docker-entrypoint.sh, testing/bin/docker-entrypoint.sh
This fixes an error that prevents jemalloc from being loaded on ARM images:
```
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu/libjemalloc.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
=> [FLINK-28057] Fix LD_PRELOAD on ARM images

1.15/scala_2.12-java11-ubuntu/Dockerfile, 1.15/scala_2.12-java11-ubuntu/release.metadata, 1.15/scala_2.12-java8-ubuntu/Dockerfile, 1.15/scala_2.12-java8-ubuntu/release.metadata
Updated the docker images taking https://github.com/apache/flink-docker/pull/128 as an example.
=> Update Dockerfiles for 1.15.3 release

.github/workflows/docker-bake.hcl
Just the docker bake file, GHA is on the master branch.
=> [FLINK-27671] Add arm support for snapshot docker images

.github/workflows/snapshot.yml, 1.17/scala_2.12-java11-ubuntu/Dockerfile, 1.17/scala_2.12-java11-ubuntu/docker-entrypoint.sh, 1.17/scala_2.12-java11-ubuntu/release.metadata, 1.17/scala_2.12-java8-ubuntu/Dockerfile, 1.17/scala_2.12-java8-ubuntu/docker-entrypoint.sh, 1.17/scala_2.12-java8-ubuntu/release.metadata, README.md
This also includes some minor documentation fixes where I removed steps that are not necessary anymore (see the commit message for the reasoning)
=> [FLINK-31566][docker] Removes 1.15 and adds 1.17 Dockerfiles

add-version.sh
The GPG key 2E0E1AB5D39D55E608071FB9F795C02A4D2482B3 can by found [here](https://dist.apache.org/repos/dist/release/flink/KEYS) with Yun Tang singed.
=> Add GPG key for 1.17.2 release

1.16/scala_2.12-java11-ubuntu/Dockerfile, 1.16/scala_2.12-java11-ubuntu/release.metadata, 1.16/scala_2.12-java8-ubuntu/Dockerfile, 1.16/scala_2.12-java8-ubuntu/release.metadata
GPG key(`B2D64016B940A7E0B9B72E0D7D0528B28037D8BC`) can be found from 1.16.3 vote mail and KEYS[2].
[1] https://lists.apache.org/thread/dxfmt3v5n0xv5r9tjl30ob5d7y5t7pw3
[2] https://dist.apache.org/repos/dist/release/flink/KEYS
=> Update Dockerfiles for 1.16.3 release

add-version.sh
GPG key(`B2D64016B940A7E0B9B72E0D7D0528B28037D8BC`)  can be found from 1.16.3 vote mail and KEYS[2].
[1]  https://lists.apache.org/thread/dxfmt3v5n0xv5r9tjl30ob5d7y5t7pw3
[2] https://dist.apache.org/repos/dist/release/flink/KEYS
=> Add GPG key for 1.16.3 release

1.18/scala_2.12-java11-ubuntu/Dockerfile, 1.18/scala_2.12-java11-ubuntu/release.metadata, 1.18/scala_2.12-java17-ubuntu/Dockerfile, 1.18/scala_2.12-java17-ubuntu/release.metadata, 1.18/scala_2.12-java8-ubuntu/Dockerfile, 1.18/scala_2.12-java8-ubuntu/release.metadata
GPG key(96AE0E32CBE6E0753CE6DF6CB078D1D3253A8D82) can be found from 1.18.1 vote mail and KEYS[2].
[1] https://lists.apache.org/thread/zkgh6c9vhk9z3072vqlxxtbvrghllcp8
[2] https://dist.apache.org/repos/dist/release/flink/KEYS
=> [FLINK-33842][docs] Update Dockerfiles for 1.18.1 release

add-version.sh
similar to https://github.com/apache/flink-docker/pull/170 but for dev-1.17
=> [FLINK-34165][1.17] update the apache download url for asc

Dockerfile-ubuntu.template, docker-entrypoint.sh
The flink-docker's Dockerfile and docker-entrypoint.sh currently use shell scripting techniques with grep and sed for configuration reading and modification. This method is not suitable for the standard YAML configuration format.
Following the changes introduced in [FLINK-33721](https://issues.apache.org/jira/browse/FLINK-33721), we should update flink-docker's Dockerfile and docker-entrypoint.sh to use BashJavaUtils for Flink configuration reading and writing.
=> [FLINK-34205] Use BashJavaUtils for Flink configuration management

1.19/scala_2.12-java11-ubuntu/Dockerfile, 1.19/scala_2.12-java11-ubuntu/docker-entrypoint.sh, 1.19/scala_2.12-java11-ubuntu/release.metadata, 1.19/scala_2.12-java17-ubuntu/Dockerfile, 1.19/scala_2.12-java17-ubuntu/docker-entrypoint.sh, 1.19/scala_2.12-java17-ubuntu/release.metadata, 1.19/scala_2.12-java8-ubuntu/Dockerfile, 1.19/scala_2.12-java8-ubuntu/docker-entrypoint.sh, 1.19/scala_2.12-java8-ubuntu/release.metadata
* Update Dockerfiles for 1.19.0 release
=> Update Dockerfiles for 1.19.0 release

add-version.sh
This is a backport pr of #185 to sync gpg key from dev-master to dev-1.19.
=> Add GPG key for 1.19.0 release

docker-entrypoint.sh
Refactor the docker-entrypoint.sh script as per the suggestions in the comments of https://github.com/docker-library/official-images/pull/16430#issuecomment-2005337882
=> [hotfix] Refactoring docker-entrypoint.sh to Use Arrays for Configuration Parameters Instead of Eval and String Concatenation

.github/workflows/snapshot.yml
[[FLINK-34419](https://issues.apache.org/jira/browse/FLINK-34419)]:  Adds support of JDK 17 & 21 for Flink 1.18+ versions in the snapshot builds.
=> [FLINK-34419][docker] Added support of JDK 17 & 21 for Flink 1.18+ 

.github/workflows/ci.yml
[[FLINK-34419](https://issues.apache.org/jira/browse/FLINK-34419)]: Updated tests to use JDK 17 and 21 versions in `dev-master`
=> [FLINK-34419][docker] Add tests for JDK 17 & 21

add-version.sh
Backport of https://github.com/apache/flink-docker/pull/190
=> [FLINK-34746] Switching to the Apache CDN for Dockerfile

add-version.sh
Update GPG key for 1.19.1 release to full key ID
Verified that lookup on pgp works
https://keyserver.ubuntu.com/pks/lookup?search=6378E37EB3AAEA188B9CB0D396C2914BB78A5EA1&fingerprint=on&op=index
=> Update GPG key for 1.19.1 release to full key ID

Dockerfile-ubuntu.template
Since FLINK-33677 will remove flink-conf.yaml from flink dist. So this PR will accordingly remove the flink-conf support.
=> [FLINK-33677][core] Remove flink-conf.yaml from flink dist.

.github/workflows/ci.yml, testing/docker-test-job/pom.xml, testing/docker-test-job/src/main/java/org/apache/flink/StreamingJob.java
For apache/flink 2.0.0 release.
=> [FLINK-37035][release] Update dev-master point to 2.1

docker-entrypoint.sh
1.19.1 release entrypoint seem to have been generated off of 1.20 release branch. This raises questions for publishing in the official-images repo
https://github.com/docker-library/official-images/pull/18452#issuecomment-2657791726
This PR syncs the dev-1.19 entrypoint with what is already out there for the 1.19.1 image
=> Align entrypoint with what was used for 1.19.1

.github/workflows/ci.yml
nightly binary release is built by jdk11 now, we should re-enable jdk11 test.
=> [hotfix] re-add jdk11 to test matrix
