.asf.yaml
As asked for in ticket [INFRA-19800](https://issues.apache.org/jira/browse/INFRA-19800).
=> Added initial .asf.yaml file for providing repository metadata

README.md, generate-stackbrew-library-docker.sh, generate-stackbrew-library.sh, testing/run_travis_tests.sh
=> [FLINK-15831] Improve documentation in README.md

1.10/scala_2.11-debian/Dockerfile, 1.10/scala_2.11-debian/docker-entrypoint.sh, 1.10/scala_2.12-debian/Dockerfile, 1.10/scala_2.12-debian/docker-entrypoint.sh, add-version.sh, generate-stackbrew-library.sh
Add GPG key and Dockerfiles for Flink 1.10.0 release
=> [FLINK-15978] Add GPG key and Dockerfiles for 1.10.0 release

testing/testing_lib.sh
De-duplicates the logic for starting JM/TM processes.
=> [FLINK-17346] De-duplicate process setup

1.10/scala_2.11-debian/Dockerfile, 1.10/scala_2.11-debian/docker-entrypoint.sh, 1.10/scala_2.12-debian/Dockerfile, 1.10/scala_2.12-debian/docker-entrypoint.sh
Checked with `docker build -t flink-1.10.1-pr-test .` and confirmed it works.
=> Update Dockerfiles for 1.10.1 release

README.md
- branch creation for major releases
- testing updates for minor releases
=> [hotfix] Extend release guide

docker-entrypoint.sh
Adds 'historyserver' as option to start the Docker container.
This option uses Flink's `start-historyserver.sh` start script to start a Flink history server.
=> [FLINK-17167] Add HistoryServer option

docker-entrypoint.sh, testing/bin/config.sh, testing/bin/docker-entrypoint.sh, testing/run_travis_tests.sh, testing/testing_lib.sh
=> [FLINK-21034] Refactor jemalloc switch to environment variable

docker-entrypoint.sh
=> [FLINK-21035] Deduplicate 'copy_plugins_if_required' calls 

docker-entrypoint.sh
Small modification to the entrypoint to prevent surprising modifications to the number of slots.
=> [FLINK-22648] Only set number of slots if env variable is set

add-version.sh, testing/run_travis_tests.sh
Update scripts to release 1.13.2
=> Release 1.13.2

add-version.sh
Add GPG key for 1.15.2 release as instructed by README
=> Add GPG key for 1.15.2 release

1.15/scala_2.12-java11-debian/Dockerfile, 1.15/scala_2.12-java11-debian/docker-entrypoint.sh, 1.15/scala_2.12-java11-debian/release.metadata, 1.15/scala_2.12-java8-debian/Dockerfile, 1.15/scala_2.12-java8-debian/docker-entrypoint.sh, 1.15/scala_2.12-java8-debian/release.metadata
Update Dockerfiles for 1.15.2 release as instructed by the README
=> Update Dockerfiles for 1.15.2 release

README.md
=> [readme] Explicitly call out copying the flink distro in Readme

.github/workflows/snapshot.yml
I kept 1.15 around for the time being
=> Adds snapshot docker builds for v1.17

.github/workflows/docker-bake.hcl, .github/workflows/snapshot.yml
Here is a successful run on my fork:
https://github.com/mbalassi/flink-docker/actions/runs/3593973278/jobs/6051630896
=> [FLINK-27671] Add arm support for snapshot docker images

1.15/scala_2.12-java11-ubuntu/Dockerfile, 1.15/scala_2.12-java11-ubuntu/release.metadata, 1.15/scala_2.12-java8-ubuntu/Dockerfile, 1.15/scala_2.12-java8-ubuntu/release.metadata
As per
- https://github.com/apache/flink-docker/tree/master
- https://cwiki.apache.org/confluence/display/FLINK/Creating+a+Flink+Release
=> Update Dockerfiles for 1.15.4 release

.github/workflows/snapshot.yml, 1.18/scala_2.12-java11-ubuntu/Dockerfile, 1.18/scala_2.12-java11-ubuntu/docker-entrypoint.sh, 1.18/scala_2.12-java11-ubuntu/release.metadata, 1.18/scala_2.12-java17-ubuntu/Dockerfile, 1.18/scala_2.12-java17-ubuntu/docker-entrypoint.sh, 1.18/scala_2.12-java17-ubuntu/release.metadata, 1.18/scala_2.12-java8-ubuntu/Dockerfile, 1.18/scala_2.12-java8-ubuntu/docker-entrypoint.sh, 1.18/scala_2.12-java8-ubuntu/release.metadata, README.md
- ~~keep 1.15, since 1.15.5 has not been released.~~ 1.15 is removed.
- small fix in the readme
=> [FLINK-32931][docker] Update Dockerfiles for 1.18.0 release

1.17/scala_2.12-java11-ubuntu/Dockerfile, 1.17/scala_2.12-java11-ubuntu/release.metadata, 1.17/scala_2.12-java8-ubuntu/Dockerfile, 1.17/scala_2.12-java8-ubuntu/release.metadata
The GPG key `2E0E1AB5D39D55E608071FB9F795C02A4D2482B3` can by found [here](https://dist.apache.org/repos/dist/release/flink/KEYS) with `Yun Tang` singed.
=> Update Dockerfiles for 1.17.2 release

add-version.sh
similar to #170 but for dev-1.16
=> [FLINK-34165][1.16] update the apache download url for asc

add-version.sh
similar to #170 but for dev-1.15
=> [FLINK-34165][1.15] update the apache download url for asc

1.15/scala_2.12-java11-ubuntu/Dockerfile, 1.15/scala_2.12-java8-ubuntu/Dockerfile, 1.16/scala_2.12-java11-ubuntu/Dockerfile, 1.16/scala_2.12-java8-ubuntu/Dockerfile, 1.17/scala_2.12-java11-ubuntu/Dockerfile, 1.17/scala_2.12-java8-ubuntu/Dockerfile, 1.18/scala_2.12-java11-ubuntu/Dockerfile, 1.18/scala_2.12-java17-ubuntu/Dockerfile, 1.18/scala_2.12-java8-ubuntu/Dockerfile
update the apache download links generated by older generator.
Reference: #170
=> [FLINK-34165] update the apache download url for asc in the dockerfiles

add-version.sh
=> [FLINK-34165] update the apache download url

1.19/scala_2.12-java11-ubuntu/docker-entrypoint.sh, 1.19/scala_2.12-java17-ubuntu/docker-entrypoint.sh, 1.19/scala_2.12-java8-ubuntu/docker-entrypoint.sh
This pr addresses the comments on https://github.com/docker-library/official-images/pull/16430
includes the improvements by https://github.com/apache/flink-docker/pull/188
=> [FLINK-34701][release] Update docker-entrypoint.sh for 1.19.0

.github/workflows/ci.yml
[[FLINK-34419](https://issues.apache.org/jira/browse/FLINK-34419)]: Updated tests to use JDK 17 version in `dev-1.18`.
=> [FLINK-34419][docker] Add tests for JDK 17

add-version.sh
Add GPG key for releasing 1.19.1 .
Key signature can be verified for "Hong Liang Teoh" here: https://dist.apache.org/repos/dist/release/flink/KEYS
=> Add GPG key for 1.19.1 release

1.19/scala_2.12-java11-ubuntu/Dockerfile, 1.19/scala_2.12-java17-ubuntu/Dockerfile, 1.19/scala_2.12-java8-ubuntu/Dockerfile
Verified key lookup successful on pgp
https://keyserver.ubuntu.com/pks/lookup?search=6378E37EB3AAEA188B9CB0D396C2914BB78A5EA1&fingerprint=on&op=index
=> Update GPG key for 1.19.1 release to full key ID

.github/workflows/snapshot.yml
Update the `snapshots.yml` GitHub workflow matrix so that Docker snapshot builds work.
=> [FLINK-37740][flink-docker] Fix GitHub snapshots workflow failure
